### PR TITLE
Add darkpopout parameter to chat embed

### LINKED ISSUE #30: Suggestion: Add Option for Dark Themed Chat
Like Twitch itself it would be nice to have multitwitch.tv's chat also be dark themed. the feature should be optional so that each user can select their own preferred chatbox color. If I had time I would make the changes myself and submit a pull request.

### PR DESCRIPTION
**Pull request by nicholi**
Alternative pull request to https://github.com/bhamrick/multitwitch/pull/40 to fix https://github.com/bhamrick/multitwitch/issues/30.

Intead of adding a UI button, just pull parameter from querystring and use on rendering template.

I think dark mode is a very desirable feature, no matter how it is enabled.

### CODE REVIEW

**Comment by bhamrick** [comment]
This is going to be a bit rough around the edges:

* If you change the open streams via the "change streams" box, the new chats will not be dark mode.
* There's no easy way to find out about dark mode or turn it on for someone who hasn't seen this pull request.

That said, dark mode has been a massively requested feature and this seems like a fine way to get it available even if it's not particularly polished. Thanks for sending the PR and sorry for not noticing it for so long!

**Comment by bhamrick** [comment]
This is live on the website now :).

**Comment by twixthehero** [comment]
thanks for this!

**Comment by twixthehero** [comment]
opened https://github.com/bhamrick/multitwitch/pull/57 to add a short description on the homepage to enable this

**Comment by ProjectXsent** [comment]
> This is going to be a bit rough around the edges:
> 
> * If you change the open streams via the "change streams" box, the new chats will not be dark mode.
> * There's no easy way to find out about dark mode or turn it on for someone who hasn't seen this pull request.
> 
> That said, dark mode has been a massively requested feature and this seems like a fine way to get it available even if it's not particularly polished. Thanks for sending the PR and sorry for not noticing it for so long!

My temp fix for the first one is go to Right Click the light themed chat, Inspect Element>Elements>Look for 

" html class="tw-root--hover js-focus-visible tw-root--theme-light" data-js-focus-visible="" lang="en-US" " 

then change the "tw-root--theme-light" to "tw-root--theme-dark" and that specific light chat would go dark mode.

**Pull request merged**
